#!/usr/bin/python

from sgmllib import SGMLParser

class URLLister(SGMLParser):
    def start_a(self, attrs):
        href = [v for k, v in attrs if k=='href']
        if href:
            print "\n".join(href)

#import urllib
#sock = urllib.urlopen("http://diveintopython.org/")

import sys
sock = open(sys.argv[1])
htmlsrc = sock.read()
sock.close()

parser = URLLister()
parser.feed(htmlsrc)
parser.close()
