#!/bin/sh
cd
fbsetbg -a ~/.usr/gui/bg.jpg
xsetroot -cursor_name left_ptr

_modmap us

#killall syndaemon
#syndaemon -dt

#killall udiskie
udiskie -f xcowsay &

killall nm-applet
nm-applet &

safeeyes &

#pkill -f indicator-cpufreq
#indicator-cpufreq &
