#!/bin/bash

RADIO_FILE="$HOME/.usr/radios"


if [ $(ps -e |grep mplayer) == ""]; then
    RADIO=$(shuf $RADIO_FILE |head -n1   )

    echo $RADIO
    mplayer -really-quiet "$RADIO"
else
    killall mplayer
fi
