#!/bin/bash

if [ "$1" = "" ]; then

    echo Available: $(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors)

    echo Current:
    for i in $(ls /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor); do
        echo - $(cat $i)
    done

else

    echo Before: $(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)

    for i in $(ls /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor); do
        echo $1 | sudo tee $i >/dev/null
    done

    echo After: $(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)

fi
