#!/bin/sh
amixer -q set Headphone 100%
xrandr --output eDP-1-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DP-0 --off --output DP-1 --off --output HDMI-0 --mode 1360x768 --pos 1920x0 --rotate normal
pacmd set-card-profile 0 output:hdmi-stereo
