#!/bin/bash

open() {
  DEV=$1
  pmount /dev/$DEV
  _terminal -e mc /media/$DEV

  ERR=$(pumount $DEV)
  if [ $? != "0" ]; then
      xcowsay "$ERR"
  else
      xcowsay "$DEV smounted"
  fi
}


mount_all() {
  IFS=$'\n'
  for i in $(lsblk -rno NAME,RM,TYPE,MOUNTPOINT |grep '1 part'); do
    NAME=$(echo $i |cut -f1 -d' ')
    POINT=$(echo $i |cut -f4 -d' ')

    if [ "$POINT" == "" ]; then
      open $NAME &
    fi
  done
}


mount_all

