#!/bin/sh

MF="-mf w=1280:h=1024:fps=10:type=png"
OVC1="-ovc lavc -lavcopts vcodec=mpeg4:vpass=1"
OVC2="-ovc lavc -lavcopts vcodec=mpeg4:mbd=2:trell:vpass=2"

#first pass
mencoder mf://shot* -nosound $(MF) $(OVC1) -o /dev/null

#second pass
mencoder mf://shot* -nosound $(MF) $(OVC2) -o movie.avi
