#!/bin/bash

open() {
  NAME="$1"
  DIR="$2"
  ln -s "$DIR" "$NAME"
  _file_manager "$NAME"

  ERR=$(udiskie-umount "$DIR" 2>&1)
  if [ $? != "0" ]; then
      xcowsay "$ERR"
  else
      xcowsay "$NAME smounted"
  fi
  rm "$NAME"
}


mount_all() {
  # Set Internal Field Separator
  IFS=$'\n'
  for i in $(udiskie-mount -a 2>&1 |grep ^mounted); do

    NAME=$(basename $(echo $i |cut -f2 -d' '))
    DIR=$(echo $i |sed 's/mounted [^ ]* on //')
    open "$NAME" "$DIR" &
  done
}


mount_all
