#!/bin/bash
#qiv-sub $1 $2 &
#exit
if [ $1 == "0" ]; then
    DUMP=$HOME/trash/$(date +PICS_%y%m%d)
    mkdir -p $DUMP 
    mv $2 $DUMP
fi;
if [ $1 == "1" ]; then
    mv $2 $HOME/
fi;
if [ $1 == "3" ]; then
    gimp $2
fi;

if [ $1 == "6" ]; then
    convert -rotate 90 $2 $2
fi
