#!/bin/bash
#qiv-sub $1 $2 &
#exit
if [ $1 == "0" ]; then
    DUMP=$HOME/trash/$(date +PICS_%y%m%d)
    mkdir -p $DUMP 
    mv "$2" $DUMP
fi;
if [ $1 == "1" ]; then
    mkdir -p selected_1
    mv "$2" selected_1/
fi;
if [ $1 == "2" ]; then
    mkdir -p selected_2
    mv "$2" selected_2/
fi;
if [ $1 == "7" ]; then
    gimp $2
fi;

if [ $1 == "6" ]; then
    convert -rotate 90 $2 $2
fi
